server:
  port: 8081
spring:
  devtools:
    restart:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/image?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&useTimezone=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456
# mybatis配置
mybatis-plus:
  #  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#日志格式
logging:
  level:
    com.niu.tebot.mapper: debug
  pattern:
    console: '%d{YYYY-MM-dd HH:mm:ss.SSS} %clr(%-5level) --- [%-15thread]%cyan(%-50logger{50}):%msg%n'

#纸 飞机配置
telegram:
  bot:
    token: 7203617407:AAGq9fe9aZSEanFkOa3oa219bEnJI_4RKY4
    username: liuxiaolon
